#' <%=ifelse(exists("pCDFlist") && pCDFlist, "@param pCDFlist a list of the supports of the CDFs of the p-values; each list item must be a numeric vector, sorted in increasing order, whose last element equals 1","") %>
#' <%=ifelse(exists("pvalues") && pvalues, "@param pvalues a numeric vector, sorted in increasing order, that either must contain the entirety of all observable values of the p-value supports (when computing critical constants) or only the observed p-values","") %>
#' <%=ifelse(exists("stepUp") && stepUp, "@param stepUp a boolean specifying whether to conduct the step-up (\\code{TRUE}) or step-down (\\code{FALSE}; the default) procedure","") %>
#' <%=ifelse(exists("support") && support, "@param support  a numeric vector, sorted in increasing order, that contains the entirety of all observable values of the p-value supports; ignored if \\code{stepUp = FALSE}","") %>
#' <%=ifelse(exists("alpha") && alpha, "@param alpha a real number strictly between 0 and 1, indicating the target FDR level","") %>
#' <%=ifelse(exists("alpha2") && alpha2, "@param alpha the target FDR level, a number strictly between 0 and 1. For \\code{*.fast} kernels, it is only necessary, if \\code{stepUp = TRUE}.","") %>
#' <%=ifelse(exists("sorted_pv") && sorted_pv, "@param sorted_pv a numeric vector containing the observed p-values, sorted in increasing order","") %>
#' <%=ifelse(exists("raw.pvalues") && raw.pvalues, "@param raw.pvalues a numeric vector of the raw observed p-values","") %>
#' <%=ifelse(exists("direction") && direction, "@param direction a character string specifying whether to conduct a step-up (\\code{\"su\"}; the default) or step-down procedure (\\code{\"sd\"})","") %>
#' <%=ifelse(exists("ret.crit.consts") && ret.crit.consts, "@param ret.crit.consts a boolean; if \\code{TRUE}, critical constants are computed and returned (this may be computationally much more intensive)","") %>
#' <%=ifelse(exists("lambda") && lambda, "@param lambda a real number strictly between 0 and 1; if \\code{lambda = NULL} (the default), \\code{lambda} is chosen to be equal to \\code{alpha}","") %>
#' <%=ifelse(exists("adaptive") && adaptive, "@param adaptive a boolean specifying whether to conduct an adaptive procedure or not","") %>
#' <%=ifelse(exists("threshold") && threshold, "@param threshold a real number strictly between 0 and 1 indicating the largest observed p-value to be considered, i.e. larger observed p-values are filtered out and subsequent computation of critical values, adjusted p-values and rejection decisions are performed under the condition that raw p-values are smaller than or equal to \\code{threshold}","") %>
