#' <%=ifelse(exists("test.results") && test.results,          "@param test.results       either a numeric vector with p-values or an R6 object of class \\code{\\link[DiscreteTests]{DiscreteTestResults}} from package \\link[DiscreteTests]{DiscreteTests} for which a discrete FDR procedure is to be performed.","") %>
#' <%=ifelse(exists("raw.pvalues") && raw.pvalues,            "@param raw.pvalues        numeric vector with raw p-values for which a discrete FDR procedure is to be performed.","") %>
#' <%=ifelse(exists("pCDFlist") && pCDFlist,                  "@param pCDFlist           list of the supports of the CDFs of the p-values; each list item must be a numeric vector, which is sorted in increasing order and whose last element equals 1.","") %>
#' <%=ifelse(exists("alpha") && alpha,                        "@param alpha              single real number strictly between 0 and 1 indicating the target FDR level.","") %>
#' <%=ifelse(exists("direction") && direction,                "@param direction          single character string specifying whether to perform a step-up (\\code{\"su\"}; the default) or step-down procedure (\\code{\"sd\"}).","") %>
#' <%=ifelse(exists("adaptive") && adaptive,                  "@param adaptive           single boolean specifying whether to conduct an adaptive procedure or not.","") %>
#' <%=ifelse(exists("ret.crit.consts") && ret.crit.consts,    "@param ret.crit.consts    single boolean specifying whether critical constants are to be computed.","") %>
#' <%=ifelse(exists("select.threshold") && select.threshold,  "@param select.threshold   single real number strictly between 0 and 1 indicating the largest raw p-value to be considered, i.e. only p-values below this threshold are considered and the procedures are adjusted in order to take this selection effect into account; if `threshold = 1` (the default), all raw p-values are selected.","") %>
#' <%=ifelse(exists("pCDFlist.indices") && pCDFlist.indices,  "@param pCDFlist.indices   list of numeric vectors containing the test indices that indicate to which raw p-value each **unique** support in `pCDFlist` belongs; ignored if the lengths of `test.results` and `pCDFlist` are equal.","") %>
#' <%=ifelse(exists("lambda") && lambda,                      "@param lambda             real number strictly between 0 and 1 specifying the DBR tuning parameter; if `lambda = NULL` (the default), `lambda` is chosen to be equal to `alpha`.","") %>
#' <%=ifelse(exists("triple.dots") && triple.dots,            "@param ...                further arguments to be passed to or from other methods. They are ignored here.","") %>
#'
#' <%=ifelse(exists("pvalues") && pvalues,                    "@param pvalues            numeric vector, sorted in increasing order, that either must contain the entirety of all observable values of the p-value supports (when computing critical constants) or only the sorted raw p-values.","") %>
#' <%=ifelse(exists("stepUp") && stepUp,                      "@param stepUp             boolean specifying whether to conduct the step-up (`TRUE`) or step-down (`FALSE`; the default) procedure.","") %>
#' <%=ifelse(exists("support") && support,                    "@param support            numeric vector, sorted in increasing order, that contains the entirety of all observable values of the p-value supports; for `*.fast` kernels, it is ignored if `stepUp = FALSE`.","") %>
#' <%=ifelse(exists("alpha2") && alpha2,                      "@param alpha              single real number strictly between 0 and 1 indicating the target FDR level; for `*.fast` kernels, it is only needed, if `stepUp = TRUE`.","") %>
#' <%=ifelse(exists("sorted_pv") && sorted_pv,                "@param sorted_pv          numeric vector containing the raw p-values, sorted in increasing order.","") %>
#' <%=ifelse(exists("lambda2") && lambda2,                    "@param lambda             real number strictly between 0 and 1 specifying the DBR tuning parameter.","") %>
#' <%=ifelse(exists("pCDFcounts") && pCDFcounts,              "@param pCDFcounts         integer vector of counts that indicates to how many p-values each **unique** p-value distributions belongs.","") %>
#' 
#' <%=ifelse(exists("dat") && dat,                            "@param dat                input data; must be suitable for the first parameter of the provided `preprocess.fun` function or, if `preprocess.fun` is `NULL`, for the first parameter of the `test.fun` function.","") %>
#' <%=ifelse(exists("test.fun") && test.fun,                  "@param test.fun           function **from package [`DiscreteTests`][DiscreteTests::DiscreteTests-package]**, i.e. one whose name ends with `*.test.pv` and which performs hypothesis tests and provides an object with p-values and their support sets; can be specified by a single character string (which is automatically checked for being a suitable function **from that package** and may be abbreviated) or a single function object.","") %>
#' <%=ifelse(exists("test.args") && test.args,                "@param test.args          optional named list with arguments for `test.fun`; the names of the list fields must match the test function's parameter names. The first parameter of the test function MUST NOT be included!","") %>
#' <%=ifelse(exists("preprocess.fun") && preprocess.fun,      "@param preprocess.fun     optional function for pre-processing the input `data`; its result must be suitable for the first parameter of the `test.fun` function.","") %>
#' <%=ifelse(exists("preprocess.args") && preprocess.args,    "@param preprocess.args    optional named list with arguments for `preprocess.fun`; the names of the list fields must match the pre-processing function's parameter names. The first parameter of the test function MUST NOT be included!","") %>
#' 
