#' <%=ifelse(exists("x") && x,                                "@param x                  either a numeric vector with p-values between 0 and 1 or an R6 object of class \\code{\\link[DiscreteTests]{DiscreteTestResults}} from package \\link[DiscreteTests]{DiscreteTests} for which a discrete FDR procedure is to be performed.","") %>
#' <%=ifelse(exists("raw.pvalues") && raw.pvalues,            "@param raw.pvalues        numeric vector of the raw observed p-values.","") %>
#' <%=ifelse(exists("pCDFlist") && pCDFlist,                  "@param pCDFlist           list of the supports of the CDFs of the p-values; each list item must be a numeric vector, which is sorted in increasing order and whose last element equals 1.","") %>
#' <%=ifelse(exists("alpha") && alpha,                        "@param alpha              single real number strictly between 0 and 1 indicating the target FDR level.","") %>
#' <%=ifelse(exists("direction") && direction,                "@param direction          single character string specifying whether to conduct a step-up (\\code{\"su\"}; the default) or step-down procedure (\\code{\"sd\"}).","") %>
#' <%=ifelse(exists("adaptive") && adaptive,                  "@param adaptive           single boolean specifying whether to conduct an adaptive procedure or not.","") %>
#' <%=ifelse(exists("ret.crit.consts") && ret.crit.consts,    "@param ret.crit.consts    single boolean specifying whether critical constants are to be computed and returned.","") %>
#' <%=ifelse(exists("threshold") && threshold,                "@param threshold          single real number strictly between 0 and 1 indicating the largest observed p-value to be considered, i.e. larger observed p-values are filtered out and subsequent computation of critical values, adjusted p-values and rejection decisions are performed under the condition that raw p-values are smaller than or equal to \\code{threshold}.","") %>
#' <%=ifelse(exists("pCDFlist.indices") && pCDFlist.indices,  "@param pCDFlist.indices   list of numeric vectors containing the test indices that indicate to which p-value each \\strong{unique} support in \\code{pCDFlist} belongs; ignored if the lengths of \\code{raw.pvalues} and \\code{pCDFlist} are equal.","") %>
#' <%=ifelse(exists("lambda") && lambda,                      "@param lambda             real number strictly between 0 and 1 specifying the DBR tuning parameter; if \\code{lambda = NULL} (the default), \\code{lambda} is chosen to be equal to \\code{alpha}.","") %>
#'
#' <%=ifelse(exists("pvalues") && pvalues,      "@param pvalues     numeric vector, sorted in increasing order, that either must contain the entirety of all observable values of the p-value supports (when computing critical constants) or only the observed p-values.","") %>
#' <%=ifelse(exists("stepUp") && stepUp,        "@param stepUp      boolean specifying whether to conduct the step-up (\\code{TRUE}) or step-down (\\code{FALSE}; the default) procedure.","") %>
#' <%=ifelse(exists("support") && support,      "@param support     numeric vector, sorted in increasing order, that contains the entirety of all observable values of the p-value supports; for \\code{*.fast} kernels, it is ignored if \\code{stepUp = FALSE}.","") %>
#' <%=ifelse(exists("alpha2") && alpha2,        "@param alpha       single real number strictly between 0 and 1 indicating the target FDR level; for \\code{*.fast} kernels, it is only necessary, if \\code{stepUp = TRUE}.","") %>
#' <%=ifelse(exists("sorted_pv") && sorted_pv,  "@param sorted_pv   numeric vector containing the observed p-values, sorted in increasing order.","") %>
#' <%=ifelse(exists("lambda2") && lambda2,      "@param lambda      real number strictly between 0 and 1 specifying the DBR tuning parameter.","") %>
