# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name kernel
#' @rdname kernel
#' 
#' @title
#' Kernel functions
#' 
#' @description
#'
#' Kernel functions that transform observed p-values or their support according
#' to \[HSU\], \[HSD\], \[AHSU\], \[AHSD\] and \[HBR-\eqn{\lambda}\]. The
#' output is used by [discrete.BH] or [DBR], respectively.
#' `kernel_DBH_crit`, `kernel_ADBH_crit` and `kernel_DBR_crit` additionally
#' compute and return the critical constants. 
#' The end user should not use these functions directly.
#' 
#' **Note**: As of version 1.4, these functions are purely internal functions!
#' As a consequence, they have to be called directly via `:::`, e.g. 
#' `DiscreteFDR:::kernel_DBH_fast()`. But users should **not** rely on them, as
#' parameters (including their names, order, etc.) may be changed without
#' notice!
#' 
#' @details
#' When computing critical constants under step-down, that is, when using
#' `kernel_DBH_crit`, `kernel_ADBH_crit` or `kernel_DBR_crit` with
#' `stepUp = FALSE` (i.e. the step-down case), we still need to get transformed
#' p-values to compute the adjusted p-values.
#' 
#' @seealso
#' [discrete.BH], [fast.Discrete], [DBR]
#' 
#' @templateVar pCDFlist TRUE
#' @templateVar pvalues TRUE
#' @templateVar stepUp TRUE
#' @templateVar alpha2 TRUE
#' @templateVar support TRUE
#' @templateVar sorted_pv TRUE
#' @templateVar lambda2 TRUE
#' @template param 
#' 
#' @return
#' For `kernel.DBH.fast`, `kernel.ADBH.fast` and `kernel.DBR.fast`, a vector
#' of transformed p-values is returned. `kernel.DBH.crit`, `kernel.ADBH.crit`
#' `kernel.DBR.crit` return a list with critical constants (`$crit.consts`)
#' and transformed p-values (`$pval.transf`), but if `stepUp = FALSE`, there
#' are critical values only.
#' 
NULL

#' @rdname kernel
kernel_DBH_fast <- function(pCDFlist, pvalues, stepUp = FALSE, alpha = 0.05, support = numeric(), pCDFcounts = NULL) {
    .Call('_DiscreteFDRTest_kernel_DBH_fast', PACKAGE = 'DiscreteFDRTest', pCDFlist, pvalues, stepUp, alpha, support, pCDFcounts)
}

#' @rdname kernel
kernel_DBH_crit <- function(pCDFlist, support, sorted_pv, stepUp = FALSE, alpha = 0.05, pCDFcounts = NULL) {
    .Call('_DiscreteFDRTest_kernel_DBH_crit', PACKAGE = 'DiscreteFDRTest', pCDFlist, support, sorted_pv, stepUp, alpha, pCDFcounts)
}

#' @rdname kernel
kernel_ADBH_fast <- function(pCDFlist, sorted_pv, stepUp = FALSE, alpha = 0.05, support = numeric(), pCDFcounts = NULL) {
    .Call('_DiscreteFDRTest_kernel_ADBH_fast', PACKAGE = 'DiscreteFDRTest', pCDFlist, sorted_pv, stepUp, alpha, support, pCDFcounts)
}

#' @rdname kernel
kernel_ADBH_crit <- function(pCDFlist, support, sorted_pv, stepUp = FALSE, alpha = 0.05, pCDFcounts = NULL) {
    .Call('_DiscreteFDRTest_kernel_ADBH_crit', PACKAGE = 'DiscreteFDRTest', pCDFlist, support, sorted_pv, stepUp, alpha, pCDFcounts)
}

#' @rdname kernel
kernel_DBR_fast <- function(pCDFlist, sorted_pv, lambda = 0.05, pCDFcounts = NULL) {
    .Call('_DiscreteFDRTest_kernel_DBR_fast', PACKAGE = 'DiscreteFDRTest', pCDFlist, sorted_pv, lambda, pCDFcounts)
}

#' @rdname kernel
kernel_DBR_crit <- function(pCDFlist, support, sorted_pv, lambda = 0.05, alpha = 0.05, pCDFcounts = NULL) {
    .Call('_DiscreteFDRTest_kernel_DBR_crit', PACKAGE = 'DiscreteFDRTest', pCDFlist, support, sorted_pv, lambda, alpha, pCDFcounts)
}

